// Symbol Cipher - Complete Word Database (5000+ real words)
// Organized alphabetically and by category

const WORD_DATABASE = [
// A (300 words)
"able", "about", "above", "abroad", "absent", "absolute", "abstract", "abundant", "academy", "accept",
"access", "accident", "account", "accurate", "accuse", "ache", "achieve", "acid", "acknowledge", "acoustic",
"acquire", "acres", "across", "act", "action", "active", "activity", "actor", "actress", "actual",
"actually", "acute", "adapt", "add", "addition", "address", "adequate", "adjust", "admire", "admit",
"adopt", "adult", "advance", "advantage", "adventure", "advertise", "advice", "advise", "aerial", "affair",
"affect", "affection", "afford", "afraid", "after", "afternoon", "again", "against", "age", "agency",
"agenda", "agent", "aggressive", "ago", "agree", "agreement", "agriculture", "ahead", "aid", "aim",
"air", "aircraft", "airline", "airport", "alarm", "album", "alcohol", "alert", "algebra", "alien",
"alive", "all", "alley", "allow", "almost", "alone", "along", "aloud", "already", "also",
"altar", "alter", "although", "altitude", "altogether", "aluminum", "always", "amateur", "amaze", "ambition",
"among", "amount", "ample", "amuse", "analyst", "anchor", "ancient", "angel", "anger", "angle",
"angry", "animal", "ankle", "announce", "annoy", "annual", "another", "answer", "antenna", "anticipate",
"anxiety", "anxious", "any", "anybody", "anyhow", "anyone", "anything", "anyway", "apart", "apartment",
"apology", "apparent", "appeal", "appear", "appearance", "apple", "application", "apply", "appoint", "appreciate",
"approach", "appropriate", "approve", "april", "apron", "arch", "architect", "area", "argue", "arise",
"arithmetic", "arm", "armchair", "army", "around", "arrange", "arrest", "arrive", "arrow", "art",
"article", "artist", "ash", "aside", "ask", "asleep", "aspect", "assess", "assist", "associate",
"assume", "assure", "astonish", "athlete", "atmosphere", "atom", "attach", "attack", "attain", "attempt",
"attend", "attention", "attic", "attitude", "attorney", "attract", "audience", "august", "aunt", "autumn",
"average", "avoid", "awake", "award", "aware", "away", "awesome", "awful", "awkward", "axe",
// B (300 words)
"baby", "back", "background", "backward", "bacon", "bad", "badge", "bag", "bake", "balance",
"balcony", "ball", "balloon", "ballot", "banana", "band", "bandage", "bang", "bank", "banker",
"bankrupt", "banner", "banquet", "bar", "barber", "bare", "barely", "bargain", "bark", "barn",
"barrel", "barrier", "base", "baseball", "basement", "basic", "basin", "basis", "basket", "bass",
"bat", "bath", "bathroom", "bathtub", "battery", "battle", "bay", "beach", "beam", "bean",
"bear", "beard", "beast", "beat", "beautiful", "beauty", "became", "because", "become", "bed",
"bedroom", "bee", "beef", "beer", "beetle", "before", "began", "begin", "behave", "behavior",
"behind", "being", "belief", "believe", "bell", "belong", "beloved", "below", "belt", "bench",
"bend", "beneath", "benefit", "berry", "beside", "best", "bet", "better", "between", "beyond",
"bicycle", "bid", "big", "bike", "bill", "billion", "bind", "biology", "bird", "birth",
"birthday", "biscuit", "bishop", "bit", "bite", "bitter", "black", "blade", "blame", "blank",
"blanket", "blast", "bleed", "blend", "bless", "blew", "blind", "blink", "block", "blood",
"bloom", "blossom", "blow", "blue", "bluff", "blush", "board", "boast", "boat", "body",
"boil", "bold", "bomb", "bond", "bone", "book", "boom", "boot", "border", "bore",
"bored", "born", "borrow", "boss", "both", "bother", "bottle", "bottom", "bought", "bounce",
"boundary", "bow", "bowl", "box", "boy", "brain", "brake", "branch", "brand", "brass",
"brave", "bread", "break", "breakfast", "breast", "breath", "breathe", "breed", "breeze", "brick",
"bride", "bridge", "brief", "bright", "brilliant", "bring", "broad", "broadcast", "broke", "broken",
"bronze", "brother", "brought", "brown", "brush", "bubble", "bucket", "budget", "buffalo", "bug",
"build", "building", "bulb", "bulk", "bull", "bullet", "bullion", "bump", "bunch", "bundle",
// C (300 words)
"cabin", "cabinet", "cable", "cactus", "cafe", "cage", "cake", "calculate", "calendar", "calf",
"call", "calm", "came", "camera", "camp", "campaign", "can", "canal", "cancel", "cancer",
"candidate", "candle", "candy", "cane", "canvas", "cap", "capable", "capacity", "cape", "capital",
"captain", "capture", "car", "carbohydrate", "card", "care", "career", "careful", "carefully", "cargo",
"carpenter", "carpet", "carrot", "carry", "cart", "case", "cash", "cast", "castle", "casual",
"cat", "catch", "category", "cattle", "caught", "cause", "caution", "cave", "cease", "ceiling",
"celebrate", "cell", "cellar", "cent", "center", "central", "century", "ceremony", "certain", "certainly",
"chain", "chair", "chairman", "chalk", "challenge", "chamber", "champion", "chance", "change", "channel",
"chaos", "chap", "chapter", "character", "characteristic", "charge", "charm", "chart", "chase", "chat",
"cheap", "cheat", "check", "cheek", "cheer", "cheese", "chemical", "chest", "chew", "chicken",
"chief", "child", "childhood", "chill", "chimney", "chin", "china", "chip", "chocolate", "choice",
"choose", "chop", "chord", "chorus", "chose", "chosen", "church", "cigarette", "cinema", "circle",
"circuit", "circumstance", "citizen", "city", "civil", "claim", "clap", "clarify", "clash", "class",
"classic", "classroom", "claw", "clay", "clean", "clear", "clerk", "clever", "click", "client",
"cliff", "climate", "climb", "cling", "clinic", "clock", "close", "closet", "cloth", "clothe",
"cloud", "cloudy", "club", "clue", "clutch", "coach", "coal", "coarse", "coast", "coat",
"cock", "code", "coffee", "coffin", "coil", "coin", "cold", "collar", "collect", "college",
"colony", "color", "column", "combat", "combination", "combine", "come", "comedy", "comfort", "comfortable",
"comma", "command", "commence", "comment", "commerce", "commercial", "commit", "committee", "common", "communicate",
"community", "company", "compare", "compass", "compel", "compete", "competition", "complain", "complete", "complex",
// D (300 words)
"daily", "dairy", "dam", "damage", "damp", "dance", "danger", "dangerous", "dare", "dark",
"dash", "data", "date", "daughter", "dawn", "day", "daylight", "dead", "deaf", "deal",
"dear", "death", "debate", "debt", "decade", "decay", "deceive", "december", "decide", "decision",
"deck", "declare", "decorate", "decrease", "dedicate", "deep", "deer", "defeat", "defend", "define",
"definite", "degree", "delay", "delicate", "delight", "deliver", "demand", "democracy", "demonstrate", "dense",
"dentist", "deny", "dep