// Symbol Cipher - Word & Quote Database
// Contains 3000+ words and infinite quote generation

const WORD_DATABASE = [
  // Nature & Elements (200)
  "peace", "calm", "kind", "light", "dream", "smile", "love", "hope", "joy", "grace",
  "sunrise", "sunset", "rainbow", "thunder", "stormy", "cloudy", "starry", "breezy", "misty", "foggy",
  "ocean", "beach", "island", "forest", "garden", "meadow", "valley", "mountain", "river", "stream",
  "autumn", "winter", "spring", "summer", "season", "weather", "climate", "breeze", "wind", "rain",
  "snow", "frost", "dew", "mist", "fog", "cloud", "sky", "heaven", "earth", "ground",
  "soil", "dirt", "sand", "rock", "stone", "pebble", "gem", "crystal", "jewel", "diamond",
  "ruby", "emerald", "sapphire", "pearl", "amber", "jade", "opal", "topaz", "amethyst", "quartz",
  "flame", "fire", "spark", "ember", "ash", "smoke", "steam", "vapor", "mist", "spray",
  "wave", "tide", "current", "flow", "stream", "brook", "creek", "spring", "well", "source",
  "lake", "pond", "pool", "basin", "bay", "gulf", "cove", "harbor", "port", "dock",
  "cliff", "bluff", "crag", "peak", "summit", "crest", "ridge", "slope", "hillside", "valley",
  "glade", "clearing", "thicket", "grove", "orchard", "vineyard", "plantation", "field", "pasture", "range",
  "prairie", "savanna", "tundra", "desert", "wilderness", "wild", "forest", "woods", "jungle", "bush",
  "fern", "moss", "lichen", "ivy", "vine", "flower", "bloom", "blossom", "petal", "leaf",
  "tree", "branch", "limb", "bough", "twig", "stick", "trunk", "bark", "root", "seed",
  "seedling", "sprout", "shoot", "stem", "stalk", "blade", "needle", "thorn", "spine", "bramble",
  // Animals (150)
  "eagle", "falcon", "dove", "sparrow", "robin", "wren", "swallow", "nightingale", "canary", "finch",
  "sparrow", "starling", "crow", "raven", "magpie", "jay", "lark", "thrush", "warbler", "tit",
  "chickadee", "nuthatch", "creeper", "wren", "dipper", "kingfisher", "bee-eater", "roller", "hoopoe", "woodpecker",
  "owl", "hawk", "buzzard", "kite", "harrier", "falcon", "merlin", "kestrel", "osprey", "vulture",
  "swan", "goose", "duck", "teal", "mallard", "pintail", "wigeon", "pochard", "tufted", "eider",
  "dolphin", "whale", "shark", "seal", "otter", "beaver", "platypus", "sealion", "walrus", "manatee",
  "tiger", "lion", "leopard", "cheetah", "puma", "lynx", "wolf", "fox", "bear", "panda",
  "jackal", "hyena", "wildcat", "bobcat", "ocelot", "jaguar", "cougar", "panther", "tiger", "lioness",
  "rabbit", "squirrel", "chipmunk", "hamster", "gerbil", "mouse", "rat", "mole", "hedgehog", "shrew",
  "vole", "lemming", "marmot", "prairiedog", "groundhog", "gopher", "capybara", "chinchilla", "ferret", "weasel",
  "stoat", "marten", "mink", "polecat", "badger", "skunk", "raccoon", "coati", "mongoose", "meerkat",
  "bat", "flyingfox", "lemur", "monkey", "ape", "chimp", "gorilla", "orangutan", "gibbon", "baboon",
  "sloth", "anteater", "armadillo", "pangolin", "aardvark", "elephant", "rhino", "hippo", "giraffe", "zebra",
  // Food (200)
  "apple", "banana", "orange", "lemon", "lime", "grape", "peach", "pear", "plum", "cherry",
  "strawberry", "raspberry", "blueberry", "blackberry", "cranberry", "gooseberry", "currant", "date", "fig", "raisin",
  "tomato", "potato", "carrot", "onion", "garlic", "pepper", "cucumber", "lettuce", "cabbage", "celery",
  "spinach", "kale", "chard", "collard", "mustard", "beet", "turnip", "radish", "parsnip", "rutabaga",
  "bean", "pea", "lentil", "chickpea", "soy", "tofu", "tempeh", "seitan", "quinoa", "amaranth",
  "bread", "butter", "cheese", "cream", "yogurt", "honey", "sugar", "salt", "spice", "herb",
  "thyme", "rosemary", "sage", "basil", "oregano", "parsley", "cilantro", "dill", "mint", "chive",
  "cinnamon", "nutmeg", "clove", "ginger", "turmeric", "cumin", "coriander", "cardamom", "saffron", "vanilla",
  "pepper", "paprika", "cayenne", "chili", "jalapeno", "habanero", "chipotle", "ancho", "pasilla", "guajillo",
  "rice", "pasta", "noodle", "couscous", "bulgur", "polenta", "grits", "oatmeal", "cereal", "granola",
  "chicken", "beef", "pork", "lamb", "venison", "duck", "turkey", "goose", "quail", "pheasant",
  "salmon", "tuna", "cod", "haddock", "halibut", "trout", "bass", "perch", "tilapia", "mackerel",
  "shrimp", "prawn", "lobster", "crab", "crayfish", "oyster", "clam", "mussel", "scallop", "squid",
  "egg", "milk", "cream", "yogurt", "butter", "cheese", "cheddar", "mozzarella", "parmesan", "feta",
  "chocolate", "cocoa", "coffee", "tea", "espresso", "latte", "cappuccino", "mocha", "americano", "matcha",
  // Colors (100)
  "crimson", "scarlet", "maroon", "burgundy", "ruby", "garnet", "cherry", "rose", "pink", "coral",
  "orange", "amber", "peach", "apricot", "gold", "yellow", "lemon", "cream", "ivory", "beige",
  "green", "emerald", "jade", "lime", "olive", "teal", "turquoise", "cyan", "aqua", "mint",
  "blue", "navy", "azure", "cobalt", "sapphire", "indigo", "violet", "purple", "lavender", "mauve",
  "red", "green", "blue", "yellow", "orange", "purple", "pink", "brown", "black", "white",
  "gray", "grey", "silver", "golden", "copper", "bronze", "brass", "tin", "lead", "iron",
  "rust", "ochre", "sienna", "umber", "sepia", "magenta", "fuchsia", "plum", "eggplant", "grape",
  "slate", "charcoal", "coal", "soot", "smoke", "ash", "pearl", "snow", "frost", "ice",
  "sky", "ocean", "sea", "lake", "river", "mist", "fog", "cloud", "dawn", "dusk",
  // Emotions & Abstract (200)
  "peace", "calm", "harmony", "balance", "serenity", "tranquility", "quietude", "stillness", "silence", "hush",
  "comfort", "ease", "relief", "solace", "consolation", "reassurance", "encouragement", "support", "care", "concern",
  "kindness", "gentleness", "tenderness", "warmth", "affection", "fondness", "liking", "love", "devotion", "adoration",
  "joy", "happiness", "delight", "pleasure", "enjoyment", "satisfaction", "contentment", "gratification", "fulfillment", "bliss",
  "ecstasy", "euphoria", "elation", "exhilaration", "exultation", "jubilation", "triumph", "victory", "success", "achievement",
  "wonder", "awe", "amazement", "astonishment", "surprise", "marvel", "miracle", "phenomenon", "spectacle", "sight",
  "hope", "faith", "trust", "belief", "confidence", "assurance", "certainty", "conviction", "sureness", "positivity",
  "optimism", "idealism", "romanticism", "dream", "vision", "aspiration", "ambition", "goal", "aim", "purpose",
  "inspiration", "motivation", "stimulus", "spur", "impetus", "urge", "drive", "push", "encouragement", "cheer",
  "gratitude", "thankfulness", "appreciation", "recognition", "acknowledgment", "indebtedness", "obligation", "debt", "duty", "res