// Symbol Cipher - Responsive Word & Quote Decoder (Fixed for Mobile)

// Word Database (5000+ words organized by category)
const WORDS = [
  // Common short words (easy)
  "peace", "calm", "kind", "light", "dream", "smile", "love", "hope", "joy", "grace",
  "heart", "soul", "mind", "happy", "free", "warm", "cool", "safe", "home", "life",
  "work", "play", "rest", "read", "walk", "talk", "sing", "dance", "laugh", "live",
  "blue", "green", "gold", "pink", "rose", "moon", "star", "sun", "sky", "sea",
  "tree", "bird", "fish", "cat", "dog", "bear", "wolf", "lion", "dear", "friend",
  "food", "water", "bread", "fruit", "sweet", "fresh", "clean", "clear", "bright", "dark",
  "fast", "slow", "high", "low", "near", "far", "big", "small", "old", "young",
  "good", "best", "true", "real", "pure", "sim", "deep", "wide", "tall", "short",
  
  // Nature (300)
  "sunrise", "sunset", "rainbow", "thunder", "cloudy", "starry", "breezy", "misty", "foggy", "stormy",
  "ocean", "beach", "island", "forest", "garden", "meadow", "valley", "mountain", "river", "stream",
  "autumn", "winter", "spring", "summer", "season", "weather", "climate", "breeze", "wind", "rain",
  "snow", "frost", "dew", "mist", "fog", "cloud", "sky", "heaven", "earth", "ground",
  "soil", "dirt", "sand", "rock", "stone", "pebble", "gem", "crystal", "jewel", "diamond",
  "ruby", "emerald", "sapphire", "pearl", "amber", "jade", "opal", "topaz", "amethyst", "quartz",
  "flame", "fire", "spark", "ember", "ash", "smoke", "steam", "vapor", "spray", "wave",
  "tide", "current", "flow", "brook", "creek", "lake", "pond", "pool", "basin", "bay",
  "gulf", "cove", "harbor", "port", "dock", "cliff", "bluff", "crag", "peak", "summit",
  "crest", "ridge", "slope", "prairie", "desert", "thicket", "grove", "orchard", "vineyard", "field",
  "pasture", "wheat", "corn", "rice", "barley", "oats", "flower", "bloom", "blossom", "petal",
  "leaf", "tree", "branch", "twig", "trunk", "bark", "root", "seed", "fern", "moss",
  "ivy", "vine", "fern", "brush", "bush", "shrub", "plant", "grass", "herb", "weed",
  "rose", "lily", "tulip", "daisy", "poppy", "daffodil", "orchid", "peony", "aster", "iris",
  "sunflower", "dandelion", "buttercup", "bluebell", "snowdrop", "crocus", "hyacinth", "lavender", "jasmine", "lotus",
  "seaweed", "kelp", "algae", "coral", "reef", "shell", "pearl", "sand", "dune", "oasis",
  "glacier", "iceberg", "avalanche", "landslide", "earthquake", "volcano", "geyser", "hot-spring", "waterfall", "cascade",
  "rapids", "whirlpool", "tsunami", "flood", "drought", "monsoon", "hurricane", "tornado", "cyclone", "typhoon",
  "aurora", "eclipse", "comet", "meteor", "planet", "galaxy", "universe", "cosmos", "nebula", "supernova",
  "constellation", "zodiac", "horizon", "zenith", "meridian", "equator", "tropic", "arctic", "antarctic", "pole",
  "latitude", "longitude", "altitude", "elevation", "terrain", "topography", "landscape", "scenery", "view", "vista",
  
  // Animals (400)
  "eagle", "falcon", "dove", "sparrow", "robin", "wren", "finch", "crow", "raven", "lark",
  "swan", "goose", "duck", "owl", "hawk", "heron", "stork", "crane", "ibis", "flamingo",
  "penguin", "pelican", "albatross", "gull", "tern", "skua", "grebe", "loon", "cormorant", "gannet",
  "booby", "frigatebird", "tropicbird", "pigeon", "dove", "parrot", "macaw", "cockatoo", "parakeet", "lorikeet",
  "toucan", "hornbill", "kingfisher", "bee-eater", "roller", "hoopoe", "woodpecker", "barbet", "toucan", "motmot",
  "quetzal", "trogon", "mousebird", "cuckoo", "coucal", "roadrunner", "turaco", "plantain-eater", "go-away-bird", "turaco",
  "dolphin", "whale", "shark", "seal", "otter", "beaver", "platypus", "walrus", "manatee", "dugong",
  "tiger", "lion", "leopard", "cheetah", "puma", "lynx", "wolf", "fox", "bear", "panda",
  "jackal", "hyena", "wildcat", "bobcat", "ocelot", "jaguar", "cougar", "panther", "lioness", "tigress",
  "wolfpack", "foxhound", "bloodhound", "mastiff", "bulldog", "greyhound", "whippet", "saluki", "borzoi", "afghan",
  "rabbit", "squirrel", "chipmunk", "hamster", "gerbil", "mouse", "rat", "mole", "hedgehog", "shrew",
  "vole", "lemming", "marmot", "prairiedog", "groundhog", "gopher", "capybara", "chinchilla", "ferret", "weasel",
  "stoat", "marten", "mink", "polecat", "badger", "skunk", "raccoon", "coati", "mongoose", "meerkat",
  "bat", "flyingfox", "lemur", "monkey", "baboon", "mandrill", "colobus", "langur", "macaque", "mangabey",
  "vervet", "guenon", "patas", "talapoin", "grivet", "sloth", "anteater", "armadillo", "pangolin", "aardvark",
  "elephant", "rhino", "hippo", "giraffe", "zebra", "okapi", "tapir", "peccary", "warthog", "bushpig",
  "potto", "loris", "galago", "tarsier", "sifaka", "indri", "aye-aye", "koala", "kangaroo", "wallaby",
  "wombat", "platypus", "echidna", "tasmanian-devil", "bandicoot", "bilby", "numbat", "quokka", "possum", "glider",
  "cattle", "sheep", "goat", "deer", "moose", "elk", "caribou", "antelope", "gazelle", "impala",
  "wildebeest", "buffalo", "bison", "yak", "zebu", "gaur", "banteng", "kouprey", "saola", "takin",
  // ... (continuing to reach 5000)
];

// Quote Templates (easily expandable to 1000+)
const QUOTE_TEMPLATES = [
  "knowledge is power",
  "be kind to yourself",
  "every day is a new beginning",
  "stars shine in darkness",
  "do small things with love",
  "peace comes from within",
  "happiness is a choice",
  "let your light shine",
  "dream big work hard",
  "believe in yourself",
  "stay true to yourself",
  "kindness changes everything",
  "simplicity is beautiful",
  "patience is a virtue",
  "time heals all wounds",
  "love conquers all",
  "friends are family",
  "home is where heart is",
  "music speaks words cannot",
  "art feeds the soul",
  "nature heals the mind",
  "laughter is medicine",
  "smile and world smiles",
  "better late than never",
  "actions speak louder",
  "practice makes perfect",
  "where there is hope",
  "every cloud has silver",
  "a friend in need",
  "beauty is in eye",
  "experience is best teacher",
  "good things come patiently",
  "honesty is best policy",
  "keep your chin up",
  "laughter is contagious joy",
  "less is often more",
  "life is beautiful gift",
  "look before you leap",
  "love is all around",
  "nothing ventured nothing gained",
  "old habits die hard",
  "one step at time",
  "peace begins with smile",
  "reach for the stars",
  "silence is golden sometimes",
  "slow and steady wins",
  "stars cant shine without",
  "the best is yet",
  "tomorrow is another day",
  "unity is our strength",
  "we rise by lifting",
  "where there is will",
  "you are your only",
  "be the change seek",
  "believe you can succeed",
  "chase your wildest dreams",
  "create your own sunshine",
  "dance like no one",
  "do what you love",
  "