// Symbol Cipher - User-Provided Short Quotes Collection
const QUOTES_1000 = [
  "Be kind to yourself",
  "Peace begins within",
  "Trust your journey",
  "Breathe and release",
  "Choose gentle thoughts",
  "You are enough",
  "Protect your peace",
  "Embrace simple joys",
  "Rest when needed",
  "Grow at your pace",
  "Keep hope alive",
  "Listen to your heart",
  "Let kindness lead",
  "Celebrate small wins",
  "Quiet minds see clearly",
  "Patience reveals wisdom",
  "Calm creates clarity",
  "Gentle steps move mountains",
  "Kindness changes everything",
  "Hope grows quietly",
  "Small moments matter",
  "Stillness brings answers",
  "Peace lives inside",
  "Joy loves simplicity",
  "Grace guides the heart",
  "Soft words heal deeply",
  "Patience grows strength",
  "Kind hearts shine brightest",
  "Light follows patience",
  "Dreams grow slowly",
  "Faith fuels courage",
  "Harmony begins within",
  "Warm hearts change worlds",
  "Simple thoughts bring peace",
  "Hope lights the path",
  "Trust quiet wisdom",
  "Care deeply always",
  "Kindness returns multiplied",
  "Peace grows with gratitude",
  "Joy hides in small things",
  "Breathe and begin again",
  "Balance creates calm",
  "Wisdom walks softly",
  "Gentle hearts endure",
  "Love speaks quietly",
  "Patience builds strength",
  "Hope welcomes tomorrow",
  "Kindness opens doors",
  "Peace follows acceptance",
  "Stillness strengthens spirit",
  "Gratitude grows happiness",
  "Calm guides decisions",
  "Quiet courage rises",
  "Faith shapes tomorrow",
  "Love grows through kindness",
  "Peace welcomes understanding",
  "Grace softens hardship",
  "Simple joy heals hearts",
  "Patience nurtures growth",
  "Hope finds a way",
  "Kind words plant seeds",
  "Gentle thoughts calm storms",
  "Courage walks with kindness",
  "Balance brings harmony",
  "Wisdom favors patience",
  "Gratitude brightens life",
  "Soft hearts stay strong",
  "Trust life unfolding",
  "Peace steadies the soul",
  "Hope renews energy",
  "Kindness travels far",
  "Still waters reflect truth",
  "Gentle minds stay peaceful",
  "Love multiplies kindness",
  "Patience conquers worry",
  "Calm hearts endure",
  "Quiet faith sustains",
  "Joy grows in gratitude",
  "Peace lights the spirit",
  "Kindness shapes tomorrow",
  "Gentle courage leads",
  "Hope awakens strength",
  "Wisdom grows slowly",
  "Love begins within",
  "Calm breath restores balance",
  "Kindness grows quietly",
  "Patience steadies life",
  "Hope warms the soul",
  "Peace welcomes healing",
  "Gentle grace endures",
  "Faith nurtures courage",
  "Quiet love heals",
  "Joy follows gratitude",
  "Kind hearts flourish",
  "Balance protects peace",
  "Wisdom guides gently",
  "Calm minds prevail",
  "Kindness begins with you",
  "Peace grows through patience",
  "Gentle strength moves forward",
  "Hope whispers keep going",
  "Calm thoughts guide wisely",
  "Small joys brighten days",
  "Trust the quiet path",
  "Grace lives in patience",
  "Soft hearts change lives",
  "Love grows through giving",
  "Peace follows forgiveness",
  "Quiet strength rises slowly",
  "Kindness lights the way",
  "Hope blooms in silence",
  "Gentle faith carries on",
  "Calm moments restore balance",
  "Patience opens understanding",
  "Love nurtures courage",
  "Kind souls uplift others",
  "Peace settles restless minds",
  "Joy lives in gratitude",
  "Wisdom favors calm hearts",
  "Gentle words build bridges",
  "Trust the gentle rhythm",
  "Kindness softens every storm",
  "Hope shines through darkness",
  "Patience invites clarity",
  "Love warms the spirit",
  "Quiet courage stands firm",
  "Peace grows with acceptance",
  "Gentle kindness spreads light",
  "Calm breath clears worry",
  "Hope rises every morning",
  "Kind hearts build harmony",
  "Wisdom listens quietly",
  "Love heals slowly",
  "Patience steadies the journey",
  "Peace nourishes the soul",
  "Joy blossoms from gratitude",
  "Kindness begins small",
  "Gentle faith stays strong",
  "Hope fuels new beginnings",
  "Calm spirits see truth",
  "Love leads gently",
  "Patience strengthens resolve",
  "Peace surrounds patient hearts",
  "Kindness multiplies quietly",
  "Joy finds simple places",
  "Hope softens fear",
  "Gentle courage steps forward",
  "Calm wisdom guides choices",
  "Love grows through patience",
  "Kindness lifts heavy hearts",
  "Peace comforts the weary",
  "Hope rebuilds tomorrow",
  "Gentle light reveals paths",
  "Patience brings quiet victory",
  "Calm hearts welcome peace",
  "Love grows with kindness",
  "Joy dances with gratitude",
  "Hope carries the soul",
  "Kindness brightens darkness",
  "Peace lives in gratitude",
  "Gentle strength endures trials",
  "Patience nurtures wisdom",
  "Love speaks through kindness",
  "Calm courage moves mountains",
  "Hope steadies the heart",
  "Kind souls shine quietly",
  "Peace guards the spirit",
  "Gentle wisdom comforts hearts",
  "Patience protects inner peace",
  "Love creates harmony",
  "Joy rises from gratitude",
  "Hope rebuilds the spirit",
  "Kindness plants tomorrow",
  "Peace follows gentle hearts",
  "Calm thoughts bring clarity",
  "Gentle love restores hope",
  "Patience invites peace",
  "Kind hearts inspire change",
  "Hope breathes through faith",
  "Love grows without limits",
  "Peace strengthens courage",
  "Joy blooms through kindness",
  "Calm minds trust life",
  "Gentle patience heals wounds",
  "Hope lights silent paths",
  "Kindness nurtures life",
  "Peace lives in stillness",
  "Love carries the heart",
  "Patience shapes wisdom",
  "Joy welcomes the morning",
  "Calm faith remains steady",
  "Gentle courage inspires",
  "Kindness protects peace",
  "Hope awakens new dreams",
  "Kindness brightens quiet days",
  "Peace lives in patience",
  "Gentle hearts guide wisely",
  "Hope rises with faith",
  "Calm thoughts nurture strength",
  "Small kindness changes everything",
  "Trust the quiet wisdom",
  "Grace grows through patience",
  "Soft words carry power",
  "Love begins with kindness",
  "Peace welcomes gentle souls",
  "Quiet strength builds resilience",
  "Kindness shapes better days",
  "Hope lights hidden paths",
  "Gentle faith steadies hearts",
  "Calm moments heal slowly",
  "Patience nurtures clarity",
  "Love strengthens the spirit",
  "Kind souls uplift the world",
  "Peace calms the mind",
  "Joy grows through gratitude",
  "Wisdom listens patiently",
  "Gentle voices comfort hearts",
  "Trust your inner calm",
  "Kindness melts harshness",
  "Hope rises patiently",
  "Patience unlocks understanding",
  "Love nourishes life",
  "Quiet courage transforms fear",
  "Peace strengthens the soul",
  "Gentle kindness spreads warmth",
  "Calm breath brings clarity",
  "Hope renews the spirit",
  "Kind hearts welcome all",
  "Wisdom walks with patience",
  "Love restores weary hearts",
  "Patience steadies each step",
  "Peace embraces the present",
  "Joy shines through kindness",
  "Kindness grows in silence",
  "Gentle faith builds courage",
  "Hope begins quietly",
  "Calm spirits welcome wisdom",
  "Love guides softly",
  "Patience shapes tomorrow",
  "Peace holds steady",
  "Kindness lifts the spirit",
  "Joy rests in gratitude",
  "Hope warms the heart",
  "Gentle courage blooms slowly",
  "Calm wisdom protects peace",
  "Love expands endlessly",
  "Kindness nurtures harmony",
  "Peace softens worry",
  "Hope rises again",
  "Gentle light comforts hearts",
  "Patience reveals beauty",
  "Calm hearts welcome joy",
  "Love deepens through kindness",
  "Joy dances quietly",
  "Hope steadies the journey",
  "Kindness sparks change",
  "Peace nourishes life",
  "Gentle strength inspires growth",
  "Patience builds calm",
  "Love brightens every moment",
  "Calm courage holds steady",
  "Hope sustains the soul",
  "Kind spirits share warmth",
  "Peace nurtures the heart",
  "Gentle wisdom leads forward",
  "Patience invites calm",
  "Love comforts the weary",
  "Joy lives within",
  "Hope lights every dawn",
  "Kindness blesses the world",
  "Peace restores balance",
  "Calm hearts trust life",
  "Gentle love grows strong",
  "Patience shapes peaceful minds",
  "Hope breathes quietly",
  "Kindness spreads light",
  "Peace anchors the soul",
  "Love moves gently",
  "Joy blooms patiently",
  "Hope carries courage",
  "Calm thoughts create harmony",
  "Gentle grace inspires peace",
  "Patience steadies the spirit",
  "Love nurtures hope",
  "Kind hearts shine bright",
  "Peace strengthens compassion",
  "Joy welcomes every sunrise",
  "Hope awakens courage",
  "Calm wisdom nurtures growth",
  "Gentle kindness leads forward",
  "You deserve gentle days",
  "You deserve deep peace",
  "You deserve quiet happiness",
  "You deserve soft mornings",
  "You deserve kind words",
  "You deserve to rest",
  "You deserve better days",
  "You deserve calm moments",
  "You deserve patient love",
  "You deserve inner peace",
  "You are worthy of peace",
  "You are worthy of kindness",
  "You are worthy of rest",
  "You are worthy of joy",
  "You are worthy of patience",
  "You are worthy of love",
  "You are worthy of calm",
  "You are worthy of healing",
  "You are worthy of happiness",
  "You are worthy of hope",
  "Your peace matters",
  "Your heart matters",
  "Your feelings matter",
  "Your rest matters",
  "Your calm matters",
  "Your healing matters",
  "Your joy matters",
  "Your kindness matters",
  "Your story matters",
  "Your growth matters",
  "You are allowed to rest",
  "You are allowed to heal",
  "You are allowed to pause",
  "You are allowed to breathe",
  "You are allowed to grow",
  "You are allowed to change",
  "You are allowed to slow down",
  "You are allowed to begin again",
  "You are allowed to choose peace",
  "You are allowed to protect peace",
  "Take life gently",
  "Take today slowly",
  "Take a deep breath",
  "Take the quiet path",
  "Take time to heal",
  "Take rest seriously",
  "Take peace seriously",
  "Take small steps forward",
  "Take care of yourself",
  "Take the calm road",
  "Better days are coming",
  "Gentle days will return",
  "Peace will find you",
  "Calm will return",
  "Joy will return",
  "Light will return",
  "Hope will return",
  "Kindness will return",
  "Strength will return",
  "Balance will return",
  "You will feel better",
  "You will find peace",
  "You will grow stronger",
  "You will heal slowly",
  "You will rise again",
  "You will be okay",
  "You will find calm",
  "You will find clarity",
  "You will find joy",
  "You will find balance",
  "Your heart is strong",
  "Your spirit is gentle",
  "Your mind deserves rest",
  "Your soul deserves peace",
  "Your story continues",
  "Your light still shines",
  "Your path still opens",
  "Your strength still grows",
  "Your hope still lives",
  "Your peace still waits",
  "Kindness begins within you",
  "Peace lives within you",
  "Strength grows within you",
  "Hope grows within you",
  "Calm lives within you",
  "Healing begins within you",
  "Love begins within you",
  "Joy grows within you",
  "Balance grows within you",
  "Light lives within you",
  "Soft hearts stay strong",
  "Gentle souls endure",
  "Kind hearts heal",
  "Calm minds prevail",
  "Peaceful hearts shine",
  "Patient hearts grow",
  "Loving hearts endure",
  "Hopeful hearts rise",
  "Quiet hearts listen",
  "Wise hearts guide",
  "Relax you are safe here",
  "Everything will be okay",
  "You are not alone",
  "You are safe now",
  "You are safe here",
  "You are safe to rest",
  "You are safe to breathe",
  "You are safe to heal",
  "You are safe to pause",
  "You are safe to relax",
  "It is okay to rest",
  "It is okay to pause",
  "It is okay to breathe",
  "It is okay to slow down",
  "It is okay to heal",
  "It is okay to feel",
  "It is okay to begin again",
  "It is okay to take time",
  "It is okay to be gentle",
  "It is okay to let go",
  "You can rest now",
  "You can breathe slowly",
  "You can take a break",
  "You can let go",
  "You can feel calm",
  "You can find peace",
  "You can start again",
  "You can take your time",
  "You can be gentle",
  "You can be at peace",
  "The storm will pass",
  "This feeling will pass",
  "The pain will soften",
  "The mind will settle",
  "The heart will heal",
  "The night will pass",
  "The calm will return",
  "The light will return",
  "The peace will return",
  "The joy will return",
  "A calm moment awaits",
  "A peaceful moment comes",
  "A better day arrives",
  "A gentle day begins",
  "A quiet moment comes",
  "A peaceful breath begins",
  "A calm path opens",
  "A new hope rises",
  "A soft morning comes",
  "A peaceful night waits",
  "Peace is near",
  "Calm is near",
  "Hope is near",
  "Healing is near",
  "Rest is near",
  "Relief is near",
  "Balance is near",
  "Comfort is near",
  "Light is near",
  "Joy is near",
  "You deserve calm",
  "You deserve peace",
  "You deserve kindness",
  "You deserve patience",
  "You deserve rest",
  "You deserve healing",
  "You deserve gentleness",
  "You deserve understanding",
  "You deserve quiet happiness",
  "You deserve soft days",
  "Your heart deserves peace",
  "Your mind deserves rest",
  "Your soul deserves calm",
  "Your spirit deserves kindness",
  "Your life deserves balance",
  "Your days deserve gentleness",
  "Your path deserves patience",
  "Your healing deserves time",
  "Your heart deserves care",
  "Your story deserves compassion",
  "Breathe and feel calm",
  "Breathe and feel peace",
  "Breathe and release tension",
  "Breathe and soften gently",
  "Breathe and slow down",
  "Breathe and let go",
  "Breathe and trust life",
  "Breathe and welcome peace",
  "Breathe and rest quietly",
  "Breathe and feel safe",
  "You matter more than you think",
  "Your peace matters deeply",
  "Your rest truly matters",
  "Your calm truly matters",
  "Your healing truly matters",
  "Your heart truly matters",
  "Your presence truly matters",
  "Your kindness truly matters",
  "Your life truly matters",
  "Your wellbeing truly matters",
  "Kindness always finds its way back",
  "Quiet moments restore the spirit",
  "Gentle hearts carry great strength",
  "Peace grows in patient places",
  "Hope often begins in silence",
  "A calm mind sees clearly",
  "Soft words hold quiet power",
  "Gratitude brightens ordinary days",
  "Small joys build lasting happiness",
  "A peaceful heart guides wisely",
  "Light returns after dark nights",
  "Patience reveals hidden blessings",
  "Simple living brings deeper joy",
  "A gentle spirit travels far",
  "Peaceful thoughts create steady days",
  "Calm waters reflect truth",
  "Rest renews tired minds",
  "True strength moves quietly",
  "Hope shines through small cracks",
  "A kind heart never wastes effort",
  "Peace is built slowly",
  "Calm breath softens worry",
  "Grace grows through patience",
  "Joy hides in simple things",
  "Warm hearts change cold days",
  "Quiet courage reshapes fear",
  "Patience builds unseen bridges",
  "Kindness leaves lasting footprints",
  "Stillness brings understanding",
  "Hope grows with every sunrise",
  "Peace blooms where gratitude lives",
  "A steady heart walks further",
  "Small kindness carries great weight",
  "Light appears when minds rest",
  "Calm choices create peaceful paths",
  "Gentle patience wins long journeys",
  "A hopeful mind invites miracles",
  "Peace settles patient souls",
  "Wisdom listens before speaking",
  "Joy grows where kindness lives",
  "Faith travels through quiet courage",
  "Rested minds see brighter paths",
  "Calm hearts welcome new beginnings",
  "True peace needs no noise",
  "A hopeful spirit never fades",
  "Simple gratitude multiplies joy",
  "Gentle actions echo widely",
  "Kindness plants tomorrow’s happiness",
  "Patience shapes quiet strength",
  "Peaceful thoughts soften storms",
  "A quiet soul shines brightly",
  "Hope patiently builds tomorrow",
  "Warmth spreads through kindness",
  "Rest strengthens the spirit",
  "A calm path leads further",
  "Kind hearts create safe places",
  "Gentle wisdom guides softly",
  "Peace arrives through patience",
  "Soft courage moves forward",
  "Joy visits grateful hearts",
  "Stillness strengthens perspective",
  "Hope rises in quiet hearts",
  "A patient mind sees clearly",
  "Kindness travels beyond distance",
  "Peace follows gentle choices",
  "A humble heart learns deeply",
  "Joy often whispers softly",
  "True calm lives within",
  "Patience uncovers hidden paths",
  "Kindness writes lasting stories",
  "Quiet strength outlasts storms",
  "Grateful hearts live richer",
  "A calm soul shines quietly",
  "Gentle hope guides forward",
  "Peace grows through understanding",
  "Kind thoughts warm the world",
  "A hopeful heart rests easier",
  "Soft patience builds resilience",
  "Joy flourishes in gratitude",
  "True kindness needs no witness",
  "Peaceful days grow slowly",
  "Calm spirits see further",
  "Hope quietly shapes destiny",
  "Gentle wisdom softens hardship",
  "Kindness brightens heavy days",
  "Rested hearts love deeper",
  "Peace grows through acceptance",
  "A patient heart stands steady",
  "Calm voices heal wounds",
  "Quiet hope fuels courage",
  "Gentle strength carries forward",
  "Gratitude transforms ordinary life",
  "Peaceful hearts welcome tomorrow",
  "Kindness softens every edge",
  "Hope glows through darkness",
  "A calm mind protects joy",
  "Peace begins with one breath",
  "Small steps still move forward",
  "Gentle days heal tired hearts",
  "Kind words travel far",
  "Quiet mornings bring clarity",
  "Patience makes life softer",
  "Hope grows in small places",
  "A calm mind rests easier",
  "Kindness warms the soul",
  "Peaceful thoughts lighten burdens",
  "Every sunrise brings possibility",
  "Soft moments restore balance",
  "Calm hearts make wise choices",
  "Joy grows slowly",
  "A gentle life feels lighter",
  "Hope follows patience",
  "Kindness brightens dark days",
  "Simple joys fill empty spaces",
  "Peace arrives quietly",
  "Stillness helps the heart listen",
  "Kindness makes the world softer",
  "Gentle strength lasts longer",
  "Hope returns with light",
  "Calm thoughts steady the mind",
  "Quiet courage changes lives",
  "Peaceful moments matter most",
  "Kind hearts leave warmth behind",
  "Hope lives in tomorrow",
  "A slow breath changes everything",
  "Joy often comes quietly",
  "Patience calms restless minds",
  "Kindness always matters",
  "Peaceful minds see clearly",
  "Hope rises every morning",
  "Simple kindness means everything",
  "Calm brings clearer paths",
  "A gentle heart goes far",
  "Joy grows through gratitude",
  "Hope lights the road ahead",
  "Peace grows with patience",
  "Kindness changes small moments",
  "Calm choices build better days",
  "Gentle patience wins slowly",
  "Hope shines in silence",
  "Kind hearts guide the way",
  "Peace welcomes tired souls",
  "Small joys bring big comfort",
  "Quiet minds feel lighter",
  "Kindness heals quietly",
  "Hope waits around corners",
  "Calm spirits stand steady",
  "Peaceful days grow slowly",
  "A soft heart stays strong",
  "Hope finds patient hearts",
  "Kindness opens many doors",
  "Peace lives in acceptance",
  "Gentle thoughts ease worry",
  "Joy finds grateful hearts",
  "Calm hearts travel farther",
  "Hope grows with faith",
  "Kindness brings warmth",
  "Peace steadies the spirit",
  "Simple kindness matters most",
  "Gentle hope keeps rising",
  "Calm breath restores balance",
  "Kind hearts shine quietly",
  "Peace softens every storm",
  "Hope carries the soul",
  "Joy brightens ordinary days",
  "Kindness travels quietly",
  "Calm thoughts guide the day",
  "Hope strengthens the heart",
  "Peace brings gentle strength",
  "Kind words lift spirits",
  "Joy grows in patience",
  "Calm minds welcome wisdom",
  "Hope lights dark paths",
  "Peace nurtures the soul",
  "Kind hearts build bridges",
  "Gentle courage moves forward",
  "Calm moments matter deeply",
  "Hope renews tired hearts",
  "Kindness softens hard days",
  "Peace grows within silence",
  "Joy lives in gratitude",
  "Calm hearts bring harmony",
  "Hope steadies every step",
  "Kindness makes life brighter",
  "Peace warms the spirit",
  "Gentle patience shapes tomorrow",
  "Calm thoughts welcome peace",
  "Hope opens new doors",
  "Kind hearts comfort others",
  "Peaceful minds rest easier",
  "Joy appears in simple things",
  "Kindness carries quiet power",
  "Gentle days bring quiet healing",
  "Kindness leaves a warm trail",
  "Peace grows in quiet spaces",
  "Hope wakes with the sun",
  "Calm hearts move wisely",
  "Simple kindness changes lives",
  "Soft moments matter most",
  "Patience brings steady peace",
  "Kind words stay forever",
  "Hope rises with light",
  "A calm life feels lighter",
  "Small kindness builds trust",
  "Peace rests in silence",
  "Joy appears unexpectedly",
  "Kind hearts see goodness",
  "Calm minds find answers",
  "Hope grows quietly",
  "Gentle living feels peaceful",
  "Kindness softens heavy days",
  "Peace begins in stillness",
  "Joy lives in gratitude",
  "Hope returns every morning",
  "Kindness brightens the road",
  "Calm choices bring balance",
  "Peace finds patient hearts",
  "Soft strength lasts longer",
  "Hope lights hidden paths",
  "Kindness travels quietly",
  "Gentle days feel brighter",
  "Peace lives within",
  "Joy grows in kindness",
  "Calm thoughts steady life",
  "Hope welcomes tomorrow",
  "Kind hearts build comfort",
  "Peaceful living feels lighter",
  "Simple kindness heals hearts",
  "Calm spirits stand strong",
  "Hope opens gentle doors",
  "Peace rises slowly",
  "Kindness changes everything",
  "Joy warms the day",
  "Gentle patience wins",
  "Hope finds its way",
  "Calm hearts hold wisdom",
  "Kindness never fades",
  "Peace flows quietly",
  "Joy brightens simple days",
  "Hope keeps moving forward",
  "Kind hearts inspire goodness",
  "Calm breath restores peace",
  "Gentle strength grows daily",
  "Peace comforts the soul",
  "Kindness spreads warmth",
  "Hope shines softly",
  "Joy fills quiet moments",
  "Calm paths lead forward",
  "Kind hearts stay bright",
  "Peace welcomes rest",
  "Hope brings new light",
  "Gentle kindness changes days",
  "Joy arrives in small ways",
  "Calm hearts trust time",
  "Kindness carries light",
  "Peace brings clarity",
  "Hope strengthens courage",
  "Gentle days feel safe",
  "Kindness heals slowly",
  "Joy waits in gratitude",
  "Calm thoughts ease worry",
  "Hope grows stronger",
  "Peace holds steady",
  "Kind hearts guide gently",
  "Soft patience brings calm",
  "Joy lives in kindness",
  "Hope keeps rising",
  "Calm spirits welcome peace",
  "Kindness warms every room",
  "Peaceful thoughts heal hearts",
  "Gentle courage moves forward",
  "Hope steadies the heart",
  "Joy loves simple moments",
  "Calm brings quiet strength",
  "Kindness brightens paths",
  "Peace nurtures life",
  "Hope whispers softly",
  "Gentle strength keeps going",
  "Kind hearts lift others",
  "Peace rests in patience",
  "Joy grows quietly",
  "Calm minds see clearly",
  "Hope travels gently",
  "Kindness changes hearts",
  "Peace brings gentle light",
  "Joy brightens the spirit",
  "Calm moments restore balance",
  "Hope lights tomorrow",
  "Kind hearts leave goodness",
  "knowledge is power",
  "be kind to yourself",
  "every day is a new beginning",
  "stars shine in darkness",
  "do small things with love",
  "peace comes from within",
  "happiness is a choice",
  "let your light shine",
  "dream big work hard",
  "believe in yourself",
  "stay true to yourself",
  "kindness changes everything",
  "simplicity is beautiful",
  "patience is a virtue",
  "time heals all wounds",
  "love conquers all",
  "friends are family",
  "home is where heart is",
  "music speaks words cannot",
  "art feeds the soul",
  "nature heals the mind",
  "laughter is medicine",
  "smile and world smiles",
  "better late than never",
  "actions speak louder",
  "practice makes perfect",
  "where there is hope",
  "every cloud has silver",
  "a friend in need",
  "beauty is in eye",
  "experience is best teacher",
  "good things come patiently",
  "honesty is best policy",
  "keep your chin up",
  "laughter is contagious joy",
  "less is often more",
  "life is beautiful gift",
  "look before you leap",
  "love is all around",
  "nothing ventured nothing gained",
  "old habits die hard",
  "one step at time",
  "peace begins with smile",
  "reach for the stars",
  "silence is golden sometimes",
  "slow and steady wins",
  "stars cant shine without",
  "the best is yet",
  "tomorrow is another day",
  "unity is our strength",
  "we rise by lifting",
  "where there is will",
  "you are your only",
  "be the change seek",
  "believe you can succeed",
  "chase your wildest dreams",
  "create your own sunshine",
  "dance like no one",
  "do what you love",
  "embrace the glorious mess",
  "find joy in journey",
  "give more than take",
  "inspire someone every day",
  "keep going keep growing",
  "learn something new daily",
  "make today count always",
  "never give up hope",
  "progress not perfection matters",
  "rise above the storm",
  "shine your light bright",
  "start where you are",
  "stay humble work hard",
  "strength comes from struggle",
  "today is your opportunity",
  "trust the timing everything",
  "wake up be awesome",
  "walk your own path",
  "wander often wonder always",
  "what we think we",
  "your attitude determines direction",
  "be fearless in pursuit",
  "collect moments not things",
  "difficult roads lead beautiful",
  "every moment matters greatly",
  "a bird in hand",
  "a chain is only",
  "a friend in need",
  "a journey begins with step",
  "a penny saved is",
  "a picture is worth",
  "a rolling stone gathers",
  "a stitch in time",
  "absence makes heart grow",
  "actions speak louder than",
  "after storm comes calm",
  "all good things come",
  "all is well that ends well",
  "all that glitters is not gold",
  "an apple a day",
  "an ounce of prevention",
  "as you sow so",
  "ask and you shall",
  "be change you wish",
  "be yourself everyone else",
  "beautiful things happen daily",
  "beautiful things take time",
  "believe you can you",
  "best preparation for tomorrow",
  "bet on yourself",
  "better an oops than",
  "bloom where you are",
  "breathe it all in",
  "count your rainbows not",
  "create the life you love",
  "creativity takes courage",
  "dare to dream big",
  "darling you are a work of art",
  "difficult roads often lead",
  "do less with more",
  "do something today that your future self will thank",
  "do what makes your soul shine",
  "do your thing",
  "doubt kills more dreams",
  "every accomplishment starts with",
  "every day is fresh start",
  "every moment is a fresh beginning",
  "everything you can imagine is real",
  "fall in love with taking care of yourself",
  "find beauty in everything",
  "focus on the good",
  "follow your heart but take your brain",
  "good things take time",
  "grow through what you go through",
  "happiness is a journey not a destination",
  "happiness is an inside job",
  "hope is a waking dream",
  "i can and i will",
  "if not now then when",
  "if opportunity doesnt knock build a door",
  "if you can dream it",
  "if you want to be happy be",
  "it always seems impossible until",
  "it is never too late to be what",
  "joy is the simplest form of gratitude",
  "keep going you are getting there",
  "keep your face always toward the sunshine",
  "life is tough but so are you",
  "little by little one travels far",
  "live less out of habit",
  "live the life you love",
  "look for something positive",
  "make each day your masterpiece",
  "make it happen",
  "make yourself a priority",
  "mindset is everything",
  "new day new thoughts new strength",
  "no rain no flowers",
  "nothing is impossible the word itself says",
  "once you choose hope anythings possible",
  "one day or day one",
  "positive mind positive vibes positive life",
  "she believed she could",
  "small steps every day",
  "start each day with a grateful heart",
  "stay close to people who feel like sunshine",
  "stay positive work hard make it happen",
  "success is a series of small wins",
  "the best way to predict the future is to create it",
  "the comeback is always stronger than the setback",
  "the only limit is your mind",
  "the secret of getting ahead is getting started",
  "there is always something to be thankful for",
  "think positive and positive things will happen",
  "today is your opportunity",
  "we rise by lifting others",
  "when you focus on the good the good increases",
  "work hard stay humble be kind",
  "you are amazing remember that",
  "you are capable of amazing things",
  "you are stronger than you think",
  "you are the author of your own life story",
  "you attract what you are ready for",
  "you can totally do this",
  "you did not come this far to only come this far",
  "you do not fail you just learn",
  "you glow differently when you are happy",
  "your life is as good as your mindset",
  "your only limit is you",
  "a champion is defined not by their wins but by how they can recover",
  "a change is as good as a rest",
  "a comfort zone is a beautiful place but nothing ever grows there",
  "a diamond is a chunk of coal that did well under pressure",
  "a goal properly set is halfway reached",
  "a good plan today is better than a perfect plan tomorrow",
  "a hero is an ordinary individual who finds the strength to persevere",
  "a journey of a thousand miles begins with a single step",
  "a life of sacrifice is the pinnacle of art and is full of true joy",
  "a man who stands for nothing will fall for anything",
  "a person who never made a mistake never tried anything new",
  "a problem is a chance for you to do your best",
  "a river cuts through rock not because of its power but because of its persistence",
  "a ship in harbor is safe but that is not what ships are built for",
  "a smooth sea never made a skilled sailor",
  "a winner is a dreamer who never gives up",
  "aim for the moon if you miss you may hit a star",
  "all our dreams can come true if we have the courage to pursue them",
  "all progress takes place outside the comfort zone",
  "almost everything will work again if you unplug it for a few minutes including you",
  "always be yourself unless you can be a unicorn then always be a unicorn",
  "ambition is the path to success persistence is the vehicle you arrive in",
  "and so the adventure begins",
  "and though she be but little she is fierce",
  "as long as you think you can you can",
  "aspire not to have more but to be more",
  "attitude determines altitude",
  "be a voice not an echo",
  "be afraid and do it anyway",
  "be brave enough to suck at something new",
  "be fierce be kind and stay humble",
  "be gentle with yourself you are doing the best you can",
  "be happy it drives people crazy",
  "be in love with your life every minute of it"
];

// Export for use in game
if (typeof module !== "undefined" && module.exports) {
  module.exports = { QUOTES_1000 };
}
