// Symbol Cipher - 1000 Inspirational Quotes

const QUOTES_1000 = [
  "knowledge is power","be kind to yourself","every day is a new beginning",
  "stars shine in darkness","do small things with love","peace comes from within",
  "happiness is a choice","let your light shine","dream big work hard",
  "believe in yourself","stay true to yourself","kindness changes everything",
  "simplicity is beautiful","patience is a virtue","time heals all wounds",
  "love conquers all","friends are family","home is where heart is",
  "music speaks words cannot","art feeds the soul","nature heals the mind",
  "laughter is medicine","smile and world smiles","better late than never",
  "actions speak louder","practice makes perfect","where there is hope",
  "every cloud has silver","a friend in need","beauty is in eye",
  "experience is best teacher","good things come patiently","honesty is best policy",
  "keep your chin up","laughter is contagious joy","less is often more",
  "life is beautiful gift","look before you leap","love is all around",
  "nothing ventured nothing gained","old habits die hard","one step at time",
  "peace begins with smile","reach for the stars","silence is golden sometimes",
  "slow and steady wins","stars cant shine without","the best is yet",
  "tomorrow is another day","unity is our strength","we rise by lifting",
  "where there is will","you are your only","be the change seek",
  "believe you can succeed","chase your wildest dreams","create your own sunshine",
  "dance like no one","do what you love","embrace the glorious mess",
  "find joy in journey","give more than take","inspire someone every day",
  "keep going keep growing","learn something new daily","make today count always",
  "never give up hope","progress not perfection matters","rise above the storm",
  "shine your light bright","start where you are","stay humble work hard",
  "strength comes from struggle","today is your opportunity","trust the timing everything",
  "wake up be awesome","walk your own path","wander often wonder always",
  "what we think we","your attitude determines direction","be fearless in pursuit",
  "collect moments not things","difficult roads lead beautiful","every moment matters greatly",
  "a bird in hand","a chain is only","a friend in need",
  "a journey begins with step","a penny saved is","a picture is worth",
  "a rolling stone gathers","a stitch in time","absence makes heart grow",
  "actions speak louder than","after storm comes calm","all good things come",
  "all is well that ends well","all that glitters is not gold",
  "an apple a day","an ounce of prevention","as you sow so",
  "ask and you shall","be change you wish","be yourself everyone else",
  "beautiful things happen daily","beautiful things take time","believe you can you",
  "best preparation for tomorrow","bet on yourself","better an oops than",
  "bloom where you are","breathe it all in","count your rainbows not",
  "create the life you love","creativity takes courage","dare to dream big",
  "darling you are a work of art","difficult roads often lead","do less with more",
  "do something today that your future self will thank","do what makes your soul shine",
  "do your thing","doubt kills more dreams","every accomplishment starts with",
  "every day is fresh start","every moment is a fresh beginning","everything you can imagine is real",
  "fall in love with taking care of yourself","find beauty in everything",
  "focus on the good","follow your heart but take your brain",
  "good things take time","grow through what you go through",
  "happiness is a journey not a destination","happiness is an inside job",
  "hope is a waking dream","i can and i will","if not now then when",
  "if opportunity doesnt knock build a door","if you can dream it",
  "if you want to be happy be","it always seems impossible until",
  "it is never too late to be what","joy is the simplest form of gratitude",
  "keep going you are getting there","keep your face always toward the sunshine",
  "life is tough but so are you","little by little one travels far",
  "live less out of habit","live the life you love","look for something positive",
  "make each day your masterpiece","make it happen","make yourself a priority",
  "mindset is everything","new day new thoughts new strength",
  "no rain no flowers","nothing is impossible the word itself says",
  "once you choose hope anythings possible","one day or day one",
  "positive mind positive vibes positive life","she believed she could",
  "small steps every day","start each day with a grateful heart",
  "stay close to people who feel like sunshine","stay positive work hard make it happen",
  "success is a series of small wins","the best way to predict the future is to create it",
  "the comeback is always stronger than the setback","the only limit is your mind",
  "the secret of getting ahead is getting started","there is always something to be thankful for",
  "think positive and positive things will happen","today is your opportunity",
  "we rise by lifting others","when you focus on the good the good increases",
  "work hard stay humble be kind","you are amazing remember that",
  "you are capable of amazing things","you are stronger than you think",
  "you are the author of your own life story","you attract what you are ready for",
  "you can totally do this","you did not come this far to only come this far",
  "you do not fail you just learn","you glow differently when you are happy",
  "your life is as good as your mindset","your only limit is you",
  "a champion is defined not by their wins but by how they can recover","a change is as good as a rest",
  "a comfort zone is a beautiful place but nothing ever grows there","a diamond is a chunk of coal that did well under pressure",
  "a goal properly set is halfway reached","a good plan today is better than a perfect plan tomorrow",
  "a hero is an ordinary individual who finds the strength to persevere","a journey of a thousand miles begins with a single step",
  "a life of sacrifice is the pinnacle of art and is full of true joy","a man who stands for nothing will fall for anything",
  "a person who never made a mistake never tried anything new","a problem is a chance for you to do your best",
  "a river cuts through rock not because of its power but because of its persistence",
  "a ship in harbor is safe but that is not what ships are built for","a smooth sea never made a skilled sailor",
  "a winner is a dreamer who never gives up","aim for the moon if you miss you may hit a star",
  "all our dreams can come true if we have the courage to pursue them","all progress takes place outside the comfort zone",
  "almost everything will work again if you unplug it for a few minutes including you",
  "always be yourself unless you can be a unicorn then always be a unicorn",
  "ambition is the path to success persistence is the vehicle you arrive in",
  "and so the adventure begins","and though she be but little she is fierce",
  "as long as you think you can you can","aspire not to have more but to be more",
  "attitude determines altitude","be a voice not an echo","be afraid and do it anyway",
  "be brave enough to suck at something new","be fierce be kind and stay humble",
  "be gentle with yourself you are doing the best you can","be happy it drives people crazy",
  "be in love with your life every minute of it","be messy and complicated and afraid and show